# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-action

name: Generate Cypress Report
on:
  push:
    branches:
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome Latest
    runs-on: ubuntu-18.04
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run cy:headless
        continue-on-error: true

      - name: Merge test reports
        run: npm run report:merge

      - name: Generate HTML report
        run: npm run report:generate

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
