name: Generate Cypress Report
on: [push]

jobs:
  cypress-test:
    name: Run Tests on Chrome Browser
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify

      - name: Run Cypress tests
        run: npm run cy:test
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots

      - name: Merge test reports
        run: npm run combine-reports

      - name: Generate HTML report
        run: npm run generate-report

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
