name: Cypress CI/CD With Github Page Publish
on:
  push:
    branches:
      - "mahbub"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: npm run scripts

      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-execution-report
          path: reports
          retention-days: 30

      # - name: Copy test execution videos and screenshots
      #   run: |
      #     mkdir public
      #     cp -r public/videos
      #     cp -r public/screenshots
      # - name: Merge test reports
      #   run: npm run combine-reports

      # - name: Generate HTML report
      #   run: npm run generate-report

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./cypress/reports
