name: Cypress Test Suite
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: run cypress tests with chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          browser: chrome
