name: Cypress Test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - master
  pull_request:
    branches: ["master"]

jobs:
  cypress-test:
    name: Run on Chrome 107
    runs-on: ubuntu-18.04
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
      - name: Run Cypress tests
        run: npm run scripts
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir
          cp -r cypress/videos
          cp -r cypress/screenshots
      - name: Merge test reports
        run: npm run combine-report

      - name: Generate HTML report
        run: npm run generate-report

      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          browser: chrome
